### ISSUE TITLE
Election BUG

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#373]
## Description

**Describe the bug**
The election is not appearing well.
And there is a log error in the console 

**Screenshots**
![image](https://github.com/user-attachments/assets/57b209de-e444-42b1-8ff2-c15d2205e728)

![image](https://github.com/user-attachments/assets/138dffd0-3a70-4026-ad10-0250a044777c)

**Comment by dasarathg68** [comment]
Can you elaborate more about when this error shows up?
It looks good on my end.

**Comment by hermannleboss** [comment]
I'm on develop
I create a team and try to do an election.
And on proposal i have a chart working but not on election

**Comment by farrellh1** [comment]
i had this problem before, it solved by resintalling all of the npm packages

**Comment by dasarathg68** [comment]
The error is because of your lock file.
Delete the node_modules and lock file and npm install again

**Comment by hermannleboss** [comment]
It's not fixed for me. 

But i need to make more test. 
And run it in docker
